apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cicd
  name: executor-role
rules:
  # runner 要新建 pod，所以为它赋予 pod 相关的权限
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
