# ffmpeg - http://ffmpeg.org/download.html
#
# From https://trac.ffmpeg.org/wiki/CompilationGuide/Centos
#
# https://hub.docker.com/r/jrottenberg/ffmpeg/
#
#
FROM    centos:7 AS base
#COPY    CentOS-Base.repo /tmp/.
RUN     \
#        mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.bak && \
#        mv /tmp/CentOS-Base.repo /etc/yum.repos.d/. && yum makecache && \
        yum -y install libgomp gcc-c++ make gcc git gdb && \
        yum clean all;


FROM        base AS build

WORKDIR     /tmp/workdir

ARG        PKG_CONFIG_PATH=/opt/ffmpeg/lib/pkgconfig
ARG        LD_LIBRARY_PATH=/opt/ffmpeg/lib
ARG        PREFIX=/opt/ffmpeg
ARG        MAKEFLAGS="-j2"

ENV         FFMPEG_VERSION=4.1.3     \
            SRC=/usr/local

#yasm \
RUN     buildDeps="autoconf \
                   automake \
                   bzip2 \
                   cmake \
                   expat-devel \
                   gcc \
                   gcc-c++ \
                   git \
                   gperf \
                   libtool \
                   make \
                   nasm \
                   perl \
                   openssl-devel \
                   tar \
                   swig \
                   bison \
                   python-devel \
                   which \
                   zlib-devel" && \
        echo "${SRC}/lib" > /etc/ld.so.conf.d/libc.conf && \
        yum --enablerepo=extras install -y epel-release && \
        yum install -y ${buildDeps}

FROM        build as debug
WORKDIR     /tmp/workdir
ENV         FFMPEG_VERSION=4.1.3     \
            SRC=/usr/local

COPY    ffmpeg-${FFMPEG_VERSION}.tar.bz2 pocketsphinx-5prealpha.tar.gz  sphinxbase-5prealpha.tar.gz /tmp/

RUN \
         DIR=/tmp/cmusphinx && mkdir -p ${DIR} && cd ${DIR} && mv /tmp/sphinxbase-5prealpha.tar.gz . && \
         tar -zx -f sphinxbase-5prealpha.tar.gz && mv /tmp/pocketsphinx-5prealpha.tar.gz . && \
         # tar -jx --strip-components=1 -f ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
         tar -zx -f pocketsphinx-5prealpha.tar.gz

RUN \
         DIR=/tmp/cmusphinx/sphinxbase-5prealpha && cd ${DIR} && ./autogen.sh && \
         ./configure --prefix=/opt/sphinxbase && make && make install

RUN \
         DIR=/tmp/cmusphinx/pocketsphinx-5prealpha && cd ${DIR} && ./autogen.sh && \
         ./configure --prefix=/opt/pocketsphinx && make && make install && \
         mkdir -p /opt/libpocketsphinx/include && cp ${DIR}/src/libpocketsphinx/*.h /opt/libpocketsphinx/include/.

#ARG        PKG_CONFIG_PATH=/tmp/install/ffmpeg/lib/pkgconfig
#ARG        LD_LIBRARY_PATH=/tmp/install/ffmpeg/lib
#ARG        PREFIX=/tmp/install
#ARG        MAKEFLAGS="-j2"

ARG        PKG_CONFIG_PATH=/tmp/install/lib/pkgconfig
ARG        LD_LIBRARY_PATH=/tmp/install/lib
ARG        PREFIX=/tmp/install
ARG        MAKEFLAGS="-j2"


RUN \
        DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} && mv /tmp/ffmpeg-${FFMPEG_VERSION}.tar.bz2 . && \
        tar -jx --strip-components=1 -f ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
        ./configure \
        --disable-debug \
	#--enable-debug=3 \
        #--disable-optimizations \
        #--disable-stripping \
        #--disable-asm \
        --disable-doc \
        --disable-ffplay \
        --enable-shared \
        --enable-avresample \
        --enable-gpl \
        --enable-nonfree \
        --enable-openssl \
        --extra-libs=-lpthread \
        --enable-postproc \
        --enable-small \
        --enable-version3 \
        --extra-cflags="-I${PREFIX}/include" \
        --extra-ldflags="-L${PREFIX}/lib" \
        --extra-libs=-ldl \
        --prefix="${PREFIX}" && \
        make && \
        make install && \
        make distclean && \
        hash -r && \
        cd tools && \
        make qt-faststart && \
        cp qt-faststart ${PREFIX}/bin

RUN \
    mkdir -p /tmp/install && mkdir -p /tmp/install/lib && mkdir -p /opt/ffmpeg/lib && \
    mkdir -p /opt/ffmpeg/bin && mkdir -p /opt/ffmpeg/include && mkdir -p /opt/ffmpeg/share && \
    ldd ${PREFIX}/bin/ffmpeg | grep tmp/install | cut -d ' ' -f 3 | xargs -i cp {} /opt/ffmpeg/lib && \
    cp ${PREFIX}/bin/* /opt/ffmpeg/bin && \
    cp -r ${PREFIX}/include/* /opt/ffmpeg/include/. && \
    cp -r ${PREFIX}/share/ffmpeg/* /opt/ffmpeg/share/.


FROM        base
MAINTAINER  Chen, You <chenyou.fdu@gmail.com>

#CMD         ["--help"]
#ENTRYPOINT  ["ffmpeg"]

#ENV LD_LIBRARY_PATH=/usr/local/lib64

COPY --from=debug /opt/ /opt/dep/


