apiVersion: v1
kind: Service
metadata:
  name: bert-svc
  namespace: gecmarker
  labels:
    app: bert-svc
spec:
  ports:
    - name: port-in
      port: 5555
      targetPort: 5555 
    - name: port-out
      port: 5556
      targetPort: 5556
  selector:
    app: bert-server
