apiVersion: v1
kind: Pod
metadata:
  name: app-kafka-zookeeper
  namespace: app-env
  labels:
    app: app-kafka-zookeeper
spec:
  containers:
    - name: app-zookeeper
      image: wurstmeister/zookeeper
      ports:
        - containerPort: 2181

    - name: app-kafka
      image: wurstmeister/kafka
      env:
      - name: KAFKA_LISTENERS
        value: "PLAINTEXT://app-kafka-zookeeper:9092"
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: "app-kafka-zookeeper:2181"
      - name: KAFKA_ADVERTISED_LISTENERS
        value: "PLAINTEXT://app-kafka-zookeeper:9092"
      - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL

      ports:
        - containerPort: 9092
