apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: app-env
  labels:
    app: kafka-svc
spec:
  selector:
    app: app-kafka-zookeeper
  type: NodePort
  ports:
  - name: app-zookeeper
    port: 2181
    targetPort: 2181
    nodePort: 30005
  - name: app-kafka
    port: 9092
    targetPort: 9092
    nodePort: 30006