apiVersion: v1
kind: Pod
metadata:
    name: test-app
    namespace: test-env
    labels:
        app: test-app
spec:
    # hostNetwork: true
    containers:
        - name: test-redis
          image: redis:3.2.12
          command: ["redis-server"]
          args: ["--appendonly yes", "--requirepass fupu@redis_test"]
          ports:
              - containerPort: 6379
                #hostPort: 7001

        - name: test-elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
          env:
          - name: discovery.type
            value: "single-node"
          - name: transport.tcp.port
            value: "9200"
          - name: http.port
            value: "9201"
          ports:
              - name: transport
                containerPort: 9200
              - name: http
                containerPort: 9201

        - name: test-mongodb
          image: mongo:3.4
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: fupu_mongo
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: fupu_mongodb_test
          ports:
              - containerPort: 27017

    nodeSelector:
        ecs-name: fopure00
