# 创建一个服务
apiVersion: v1
kind: Service
metadata:
    name: test-svc
    namespace: test-env
    labels:
        run: test-svc
spec:
    selector:
        app: test-app
    type: NodePort 
    ports:
    - name: test-redis
      port: 6379
      targetPort: 6379
      nodePort: 30001
    - name: test-elastic-transport
      port: 9200
      targetPort: 9200
      nodePort: 30002
    - name: test-elastic-http
      port: 9201
      targetPort: 9201
      nodePort: 30003
    - name: test-mongo
      port: 27017
      targetPort: 27017
      nodePort: 30004
